### PR TITLE
Integrate cdaguerre changes

### PR DESCRIPTION
**Pull request by moroine**
### Fix
  - Missing Content-type xml on metadata response
  - `AssertionBuilder.setNotBefore` should set `NotBefore` subjectConfirmationData and not `NotOnOrAfter`

### Add
  - Symfony 4 support
  - `AssertionBuilder` now accept setting array values

### CODE REVIEW

**Comment by moroine** [comment]
@cdaguerre I think this is better if we bring your changes here, we are not that much contributors so it's better if we try to maintain it together !

What do you think about it ?

**Comment by moroine** [comment]
@GDXbsv could you have a look at this PR ?

**Comment by cdaguerre** [comment]
@moroine sure!

**Comment by GDXbsv** [comment]
Looks good for me. But we have some crossing changes in our PRs. So @moroine  please merge them carefully.

**Comment by GDXbsv** [comment]
Looks good after the merge with develop

**Pull request merged**
